### ISSUE TITLE
Creating a custom unit now breaks

### ISSUE THREAD

**Issue by mirkovw** [mediamonks/generator-display-boilerplate#20]
@alandawi not sure but I think perhaps updating to Yeoman generator 5.6.1 may have broken this functionality. Could you take a look?

**Comment by alandawi** [comment]
I will try to see the error, as soon as I finish the documentation of the framework and other tasks. Thanks for the warning.

**Comment by alandawi** [comment]
@mirkovw I have the same problem, If I try to select the multiple units option and get the same error of @PabloCarreira. The generator doesn't ask me about the sizes, it just creates a 300x250 by default.

Also I tried to run 'npm run dev' and here is the error:

![Captura de Pantalla 2022-06-02 a la(s) 08 09 27](https://user-images.githubusercontent.com/1291730/171616764-686c1daa-0f2f-4a46-a243-e22339e48bde.png)

-- -- -- --

The quick unit works and does not limit the work, it possible to copy&paste the folder to generate new units. The critical point is not to make direct changes in master and at least do QA of those changes made before doing the merge.

**Comment by mirkovw** [comment]
Fair enough. The point of this issue is to get it fixed though - You don't have to show me screenshots that it's broken - I'm already aware of it, that's why I opened the issue here. I was hoping you could help fix it?
