### ISSUE TITLE
[BUG] Issue with exit beign used

### ISSUE THREAD

**Issue by PabloCarreira** [mediamonks/generator-display-boilerplate#27]
Hi Team!
Found a bug on our template, not a heavy one but one that can be easily overlooked, and the impact of it is big in terms of metrics.

Media Agency had the issue that the exit was not being tracked (not quantized to be exact)
This code was tested locally, uploaded to DCS, and tried on the platform (apparently looking ok), also because of the flags it was pushed to google support and approved by them. And because of this, the dev didn't get deeper into the code to see if there was an issue.

I had this issue before but didn't change the template and carrying this template like this got the dev confused and overlooked the wrong setup of the exit event.

Handlebar variable assigned here.
https://github.com/mediamonks/generator-display-boilerplate/blob/0461987365e5e2f097787923629725af94d33c1b/generators/createDisplayUnitSet/templates/shared_doubleclick/index.hbs#L12
This is not being used and we should remove it to not generate mistakes.

Banner.js here is where we generate the confusion and overwrite the window.clicktag variable, (A variable that is used by the Enabler.API), and this is why from the platform we could get to the intended link.
https://github.com/mediamonks/generator-display-boilerplate/blob/0461987365e5e2f097787923629725af94d33c1b/generators/createDisplayUnitSet/templates/shared_doubleclick/script/Banner.js#L26

And here is where we trick the platform, where it receives a trigger of the exit but the actual link is an empty variable.
https://github.com/mediamonks/generator-display-boilerplate/blob/0461987365e5e2f097787923629725af94d33c1b/generators/createDisplayUnitSet/templates/shared_doubleclick/script/Banner.js#L61

I am going to make the changes needed to clean the code and fill the mainExit variable with the correct key.

Best
Pablito

**Comment by mirkovw** [comment]
Good find @PabloCarreira !
