### ISSUE TITLE
Google rejects cloudflare

### ISSUE THREAD

**Issue by PabloCarreira** [mediamonks/generator-display-boilerplate#48]
https://github.com/mediamonks/generator-display-boilerplate/blob/e881a6c1685dfc84112f3421b67a7d69e8174033/generators/createDisplayUnitSet/templates/default/shared/index.hbs#L38C1-L38C87

It would be easier for everyone to start with the link for gsap hosted on Google. 
the one that google suggests to use => [hosted libraries](https://support.google.com/richmedia/answer/6307288?hl=en)

Should we vote?

**Comment by xaviergdiez84** [comment]
Agree!

**Comment by mm-paulie** [comment]
Yes

**Comment by mm-vasyl** [comment]
Heyy! I have just one concern about this. Is it okay (platform-wise) to use Google hosted library on a platform that is not by Google? They're kinda like `competitors`. I know it'll work anyway. Just from a legal perspective.

**Comment by xaviergdiez84** [comment]
Unless there's a restriction of usage or a specific request to use certain library from a CDN (like Google does) I believe we are good on a legal base:

IAB’s new ad portfolio from 2017: https://www.iab.com/wp-content/uploads/2017/08/IABNewAdPortfolio_FINAL_2017.pdf) (page 16 under ’Shared Libraries and Resources’, stated the following:
"Browser caching capabilities benefit all parties by eliminating the need to download previously requested resources that already exist on the user’s device. Advertisers (Creative developers) are encouraged to take advantage of browser caching functionality by linking to shared libraries hosted on the Ad Serving party’s (Publisher ad server or third-party ad server) domain that are used across campaigns.
