### ISSUE TITLE
Plain template with option for Font reletade code

### ISSUE THREAD

**Issue by PabloCarreira** [mediamonks/generator-display-boilerplate#8]
For Mondelez we use a lot the plain template, but we dont need the font tools (font loader, font sub setting, fittext) most of the times.
Could we have an option to build the plain with or without all font related code?

Thanks.

**Comment by mirkovw** [comment]
Thanks 👍 
So back to my question, don't you use fonts in Mondelez units? font subsetting / font loading is likely a useful feature for any ad that loads in fonts. And fitText is quite useful for dynamic units..

**Comment by PabloCarreira** [comment]
Comments after the call.

Agree with having some sort of library with basic templates (plain_lite, plain_drawsvg, etc..)
this will give jr ppl better insights on how the chain of events works.

Thanks

**Comment by mirkovw** [comment]
@alandawi what Pablo and I are suggesting is having a library of examples (in a different repo/repos) instead of adding yet another template to the generator. What do you think?

**Comment by alandawi** [comment]
@mirkovw mmm it can be a good idea, although if there is a structure change in the boilerplate templates, the examples should also be updated, to have consistency between both repositories.

**Comment by mirkovw** [comment]
@alandawi yeah agreed. maintenance could be an issue. But I suggest we just create a couple of examples and share them, and then we'll see. It's a relatively low level effort.. if we need to update them in 6 months time, then that's fine IMO.

**Comment by mirkovw** [comment]
I've created a 'simple' template for now which can be found here:
https://github.com/mirkovw/display-advertising-barebones-template

So if people want to start with a project that doesn't have any "bells and whistles" they can just use this. 

@PabloCarreira does this solve it (for now?)

**Comment by mirkovw** [comment]
@PabloCarreira Marking this one as solved for now!
